### ISSUE TITLE
AttributeError: 'Discriminator' object has no attribute 'module'

### ISSUE THREAD

**Issue by dzakiabd** [WentianZhang-ML/AdaptiveMix#5]
Hi, when I want to do training I get an error when I run a command like this "python generation/train.py --data="D:\TA-152020078\dataset\Glioma_128x128" --outdir="D:\TA-152020078\results" --kimg=6000 --adaptivemix=true" and the error is as follows:

Traceback (most recent call last):
  File "generation/train.py", line 546, in <module>
    main() # pylint: disable=no-value-for-parameter
  File "C:\Users\PC\.conda\envs\stylegan2-ada-fix\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\PC\.conda\envs\stylegan2-ada-fix\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\PC\.conda\envs\stylegan2-ada-fix\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\PC\.conda\envs\stylegan2-ada-fix\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\PC\.conda\envs\stylegan2-ada-fix\lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "generation/train.py", line 539, in main
    subprocess_fn(rank=0, args=args, temp_dir=temp_dir)
  File "generation/train.py", line 389, in subprocess_fn
    training_loop.training_loop(rank=rank, **args)
  File "D:\TA-152020078\AdaptiveMix\generation\training\training_loop.py", line 287, in training_loop
    loss.accumulate_gradients(phase=phase.name, real_img=real_img, real_c=real_c, gen_z=gen_z, gen_c=gen_c, sync=sync, gain=gain)
  File "D:\TA-152020078\AdaptiveMix\generation\training\loss.py", line 80, in accumulate_gradients
    gen_logits,out_mixed,mix_z = self.run_D(gen_img, gen_c, sync=False, adaptivemix_flag=True)
  File "D:\TA-152020078\AdaptiveMix\generation\training\loss.py", line 62, in run_D
    logits, out_mixed, mix_z = self.D.module.adaptive_mix(x_a,x_b,c,self.noise_std)
  File "C:\Users\PC\.conda\envs\stylegan2-ada-fix\lib\site-packages\torch\nn\modules\module.py", line 948, in __getattr__
    type(self).__name__, name))
AttributeError: 'Discriminator' object has no attribute 'module'

The device I am using:
- Windows 11
- CUDA 11.1
- RTX 4090
- conda 23.7.4 with python 3.7.16
- torch 1.8.2+cu111

Thank you.

**Comment by WentianZhang-ML** [comment]
Hi, sorry for the late reply. 

The default version of the code is for DDP training. 

If you want to use a single GPU to complete the training, you can try it by replacing `self.D.module.adaptive_mix()` with `self.D.adaptive_mix()` in line 62 of loss.py. 

Please let me know if you have other problems.

**Comment by dzakiabd** [comment]
Thank you for your message. I am pleased to inform you that the issue has been resolved, and I can now continue with my research. 

Your response and assistance are greatly appreciated.
